# CONFIG_DRM*
KCONFIG=	DRM_AMDGPU_CIK \
		DRM_AMDGPU_SI \
		DRM_AMD_DC \
		DRM_AMD_DC_FBC \
		DRM_AMD_POWERPLAY \
		DRM_FBDEV_OVERALLOC=100 \
		DRM_FBDEV_EMULATION \
		DRM_I915_ALPHA_SUPPORT \
		DRM_I915_CAPTURE_ERROR \
		DRM_LEGACY \
		DRM_LOAD_EDID_FIRMWARE \
		DRM_MIPI_DSI \
		DRM_PANEL_ORIENTATION_QUIRKS \
		DRM_VM \
		DRM_VMWGFX_FBCON

# non arch specific kconfig
KCONFIG+=	ARCH_HAVE_NMI_SAFE_CMPXCHG \
		BACKLIGHT_CLASS_DEVICE \
		COMPAT \
		DMI \
		FB \
		MTRR \
		PCI \
		PM \
		SMP

.if ${MACHINE_CPUARCH} == "aarch64"
KCONFIG+=	ACPI \
		ARM64
.endif

.if ${MACHINE_CPUARCH} == "i386" || ${MACHINE_CPUARCH} == "amd64"
KCONFIG+=	ACPI \
		ACPI_SLEEP \
		AGP \
		X86 \
		X86_PAT

.if ${MACHINE_CPUARCH} == "amd64"
KCONFIG+=	64BIT \
		AS_MOVNTDQA \
		X64_64

KCONFIG+=	DRM_AMD_DC_DCN1_0 \
		DRM_AMD_DC_DCN1_01 \
		DRM_COMPAT
.endif
.endif

.if ${MACHINE_CPUARCH} == "powerpc64"
KCONFIG+=	64BIT \
		PPC64
.endif
