#!/bin/sh

usage()
{
	cat << EOF
	Usage: `basename "$0"` patchdir
EOF

	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

mkdir -p "$1"/alreadyapplied/

scriptdir=$(dirname "$0")
log="$scriptdir/log.txt"

git log --pretty=format:'%aD %s' > "$log"

for file in "$1"/*.patch; do
	subject=$("$scriptdir/extract-commit-title-from-patch.awk" "$file")
	grep -q -F "${subject}" "$log"
	if [ $? -eq 0 ]; then
		echo "$file already applied"
		mv $file $1/alreadyapplied
	fi
done

rm "$log"
