#!/bin/sh

# Compares two trees recursively and outputs diff in git-like style.
# Both trees must be at the same VCS revision.

DEFAULT_DRM_DIR=drivers/gpu/drm

usage()
{
	cat << EOF
	Usage: `basename $0` linux_dir drm_dir
ex: `basename $0` HOME/linux/ [${DEFAULT_DRM_DIR}]
EOF

	exit 1
}

if [ $# -eq 0 -o $# -gt 2 ]; then
	usage
fi

LINUX_DIR=$1
shift
if [ $# -eq 1 ]; then
	DRM_DIR=$1
else
	DRM_DIR=${DEFAULT_DRM_DIR}
fi

if [ ! -d ${LINUX_DIR} ]; then
	echo "No directory ${LINUX_DIR}"
	exit 1
fi

if [ ! -d ${DRM_DIR} ]; then
	echo "No directory ${DRM_DIR}"
	exit 1
fi

SCRIPT_DIR=`dirname $0`

dodiff()
{
	local SCRIPT_DIR=$1
	local DRM_DIR=$2
	local LINUX_DIR=$3
	local COLOR=$4

	/usr/bin/diff -rdpu --color=${COLOR} -X ${SCRIPT_DIR}/diffignore \
		${LINUX_DIR}/${DRM_DIR} ${DRM_DIR}
}

if [ -t 1 ] ; then
	dodiff ${SCRIPT_DIR} ${DRM_DIR} ${LINUX_DIR} "always" | /usr/bin/less -MR
else
	dodiff ${SCRIPT_DIR} ${DRM_DIR} ${LINUX_DIR} "never"
fi
