#!/bin/sh

usage()
{
	cat << EOF
	Usage: `basename $0` linux_dir patch_dir rev
ex: `basename $0` HOME/linux/ /tmp/patches v5.1..v5.2
EOF

	exit 1
}

if [ $# -ne 3 ]; then
	usage
fi

LINUX_DIR=$1
shift
PATCH_DIR=$1
shift
REV=$1

if [ ! -d ${LINUX_DIR} ]; then
	echo "No directory ${LINUX_DIR}"
	exit 1
fi

mkdir -p ${PATCH_DIR}

cd ${LINUX_DIR}
git format-patch -o ${PATCH_DIR} ${REV} \
    drivers/gpu/drm/*.c \
    drivers/gpu/drm/*.h \
    drivers/gpu/drm/amd/ \
    drivers/gpu/drm/i915/ \
    drivers/gpu/drm/radeon/ \
    drivers/gpu/drm/scheduler/ \
    drivers/gpu/drm/ttm/ \
    drivers/gpu/drm/vmwgfx/ \
    drivers/*/vboxvideo/ \
    drivers/*/*/vboxvideo/ \
    drivers/dma-buf/dma-fence.c \
    drivers/dma-buf/dma-fence-array.c \
    drivers/dma-buf/dma-fence-chain.c \
    drivers/dma-buf/dma-resv.c \
    drivers/video/hdmi.c \
    include/drm/*.h \
    include/drm/ttm/ \
    include/uapi/drm/*.h \
    include/linux/hdmi.h \
    include/linux/dma-fence.h \
    include/linux/dma-fence-array.h \
    include/linux/dma-fence-chain.h \
    ':!drivers/gpu/drm/i915/gvt/*' \
    ':!drivers/gpu/drm/i915/selftests/*' \
    ':!drivers/gpu/drm/drm_gem_cma_helper*' \
    ':!drivers/gpu/drm/drm_hdcp*' \
    ':!drivers/gpu/drm/drm_kms_helper*' \
    ':!drivers/gpu/drm/drm_mipi*' \
    ':!drivers/gpu/drm/drm_of*' \
    ':!drivers/gpu/drm/drm_simple*' \
    ':!include/drm/bridge/*' \
    ':!include/drm/tinydrm/*' \
    ':!include/drm/drm_fb_cma_helper.h*' \
    ':!include/drm/drm_gem_cma*' \
    ':!include/drm/drm_gem_shmem*' \
    ':!include/drm/drm_of*' \
    ':!include/drm/gma*' \
    ':!include/uapi/drm/etnaviv*' \
    ':!include/uapi/drm/exynos_drm*' \
    ':!include/uapi/drm/lima*' \
    ':!include/uapi/drm/msm*' \
    ':!include/uapi/drm/omap*' \
    ':!include/uapi/drm/panfrost*' \
    ':!include/uapi/drm/v3d*' \
    ':!include/uapi/drm/vc4*' \
    ':!*Makefile' \
    ':!*Kconfig*'

# Fixup some paths
for file in ${PATCH_DIR}/*; do
	sed -i '' 's/\([ab]\)\/drivers\/dma-buf\/dma-fence/\1\/linuxkpi\/gplv2\/src\/linux_dmafence/' ${file}
	sed -i '' 's/\([ab]\)\/drivers\/dma-buf\/dma-fence-array/\1\/linuxkpi\/gplv2\/src\/linux_dma-fence-array/' ${file}
	sed -i '' 's/\([ab]\)\/drivers\/dma-buf\/dma-fence-chain/\1\/linuxkpi\/gplv2\/src\/linux_dma-fence-chain/' ${file}
	sed -i '' 's/\([ab]\)\/drivers\/video\/hdmi/\1\/drivers\/gpu\/drm\/linux_hdmi/' ${file}
done
