#!/bin/sh

usage()
{
	cat << EOF
	Usage: `basename $0` patchdir
EOF

	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

mkdir -p $1/alreadyapplied/
mkdir -p $1/applied/
mkdir -p $1/rej/

for file in $1/*.patch; do
	echo "Trying to apply $file"
	git am --3way ${file}
	if [ $? -ne 0 ]; then
		echo "Patch $file failed"
		mv $file $1/rej
		exit 1
	fi
	mv $file $1/applied
done
