name: Test build + kldload

on:
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "FreeBSD ${{ matrix.freebsd_src_ref }} — ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        freebsd_src_ref: ['main', 'stable/15']
        arch: ['x86_64']
        # TODO: Requires FreeBSD 15.1-RELEASE.
        # include:
        #   - vm_release: '15.1'
        #   - freebsd_src_ref: 'release/15.1.0'
        #     test_kldload: true

    steps:
      - name: Checkout drm-kmod repository
        uses: actions/checkout@v6
        with:
          path: drm-kmod

      - name: Cache FreeBSD source repository
        uses: actions/cache@v5
        with:
          path: src/.git
          key: freebsd-src-${{ matrix.freebsd_src_ref }}

      - name: Checkout FreeBSD source repository
        uses: actions/checkout@v6
        with:
          repository: freebsd/freebsd-src
          ref: ${{ matrix.freebsd_src_ref }}
          path: src

      - name: Compile drm-kmod
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.vm_release }}
          arch: ${{ matrix.arch }}
          usesh: true
          run: |
            set -ex

            export SYSDIR=$PWD/src/sys
            test -d "$SYSDIR"

            make -j$(sysctl -n hw.ncpu) -C drm-kmod
            make -C drm-kmod install

      - name: Load DRM drivers
        if: ${{ matrix.test_kldload == true }}
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.vm_release }}
          arch: ${{ matrix.arch }}
          usesh: true
          run: |
            set -ex

            # The firmwares are missing, but that's ok, there are no GPU in CI
            # anyway. The goal is just to check the modules are loadable and
            # there are no missing symbols.
            kldload amdgpu i915kms radeonkms

            cat /var/log/messages
